Handle API pagination
hashicorp/terraform-cloud-operator pull request #426
Opened 2024-06-06 23:45 UTC by jtdoepke

### Description

We encountered a bug where some workspaces that should have had run triggers added by the operator did not have them. We suspected it was due to the controller [not handling pagination](https://github.com/hashicorp/terraform-cloud-operator/blob/e7e491c3685dd445d17090fb667a8935f51e3588/controllers/workspace_controller_run_triggers.go#L31). I'm no longer sure that's the source of our bug, but it still seems reasonable that any calls to a Terraform Cloud API endpoint that is paginated should handle that pagination.

### Usage Example

N/A

### References

N/A

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

2024-07-11 14:02 UTC, arybolovlev commented
Hi @jtdoepke,

This is indeed a thing that we have missed. Could you please rebase your PR? I will then review it and we could add this fix to the 2.6.0 release(ETA this month).

Thanks!

2024-07-11 18:38 UTC, jtdoepke commented
@arybolovlev done.

2024-07-15 07:59 UTC, arybolovlev requested changes
Hi @jtdoepke,

All in all, everything looks good. Could you please add `PageSize: maxPageSize,` to the option list?

Thanks!

2024-07-17 08:42 UTC, arybolovlev approved these changes
Thank you for this fix, @jtdoepke! 🚀 It will be available in 2.6.0 release. ETA end of July.

2024-07-17 08:42 UTC, merged